name: GitHub CI

on:
  push:
    branches: '**'
    tags: '**'
  pull_request:
  schedule:
  - cron: '15 20 */2 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php_version: ['8.3', '8.2', '8.1', '8.0', '7.4']
        deployer:
        - major: '6'
          version: '6.9.0'
          sha256: 'aa07877cba8578c3fb70d1ab6ff82d5971a7dcf196d532cb14e1dd0f1c752d78'
        - major: '7'
          version: '7.5.12'
          sha256: 'b55c6609653e888c672d327c407f8bba6324b9c9cc24f9dcfb3f4b3922760632'

    steps:
    - name: Login to Docker Hub
      if: ${{ (github.event_name != 'pull_request') && (github.ref_name == github.event.repository.default_branch) }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push (deployer v6)
      if: ${{ matrix.deployer.major == '6' }}
      id: docker_build_v6
      uses: docker/build-push-action@v5
      with:
        build-args: |
          PHP_TAG_VERSION=${{ matrix.php_version }}
          DEPLOYER_VERSION=${{ matrix.deployer.version }}
          DEPLOYER_SHA256=${{ matrix.deployer.sha256 }}
        push: ${{ (github.event_name != 'pull_request') && (github.ref_name == github.event.repository.default_branch) }}
        tags: |
          letsdockerize/php:${{ matrix.php_version }}
          letsdockerize/php:${{ matrix.php_version }}-dep6

    - name: Build and push (deployer v7)
      if: ${{ matrix.deployer.major == '7' }}
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        build-args: |
          PHP_TAG_VERSION=${{ matrix.php_version }}
          DEPLOYER_VERSION=${{ matrix.deployer.version }}
          DEPLOYER_SHA256=${{ matrix.deployer.sha256 }}
        push: ${{ (github.event_name != 'pull_request') && (github.ref_name == github.event.repository.default_branch) }}
        tags: letsdockerize/php:${{ matrix.php_version }}-dep7

    - name: Image digest
      run: |
        echo ${{ steps.docker_build.outputs.digest }}
        echo "Deploying to production server on branch $GITHUB_REF  ${GITHUB_REF#refs/*/}"
