name: CI

on:
  push:
    branches: '**'
    tags: '**'
  pull_request:
  schedule:
  - cron: '0 0 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']

    steps:
    - name: Login to Docker Hub
      if: ${{ (github.event_name != 'pull_request') && (github.ref == 'refs/heads/master') }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        build-args: PHP_TAG_VERSION=${{ matrix.php_version }}
        push: ${{ (github.event_name != 'pull_request') && (github.ref == 'refs/heads/master') }}
        tags: letsdockerize/php:${{ matrix.php_version }}

    - name: Image digest
      run: |
        echo ${{ steps.docker_build.outputs.digest }}
        echo "Deploying to production server on branch $GITHUB_REF  ${GITHUB_REF#refs/*/}"
