name: Docker Image CI

on:
  push:
    branches:
      - 'master'

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build --file ./Dockerfile --build-arg "PHP_TAG_VERSION=${{ matrix.php_version }}" --tag "letsdockerize/php:${{ matrix.php_version }}" .

    - name: show image list
      run: docker image ls
