name: Schedule publish Docker Image

on:
  push:
    branches:
      - 'master'

env:
  TAG_PREFIX: $([ ${GITHUB_REF#refs/*/} == "master" ] && echo "latest" || echo ${GITHUB_REF#refs/*/})
  TAG_VERSION: echo ${PHP_VERSION:0:1}.${PHP_VERSION:1:1}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['5.6', '7.4']

    steps:
    - name: check
      run: |
        echo ${{ env.TAG_PREFIX }}
        echo ${{ env.TAG_VERSION }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: letsdockerize/php:${{ env.TAG_PREFIX }}-${{ env.TAG_VERSION }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
